### ISSUE TITLE
Классы и данные

### ISSUE THREAD

**Issue by acrm** [Rideress/JavaLearning#2]
Сейчас мы имеем программу, состоящую из набора классов и методов, описывающую устройство компьютера. Но по большому счёту, сейчас классы, как мы их используем, - это просто пространства имён, позволяющие дать имена разным наборам методов, чтобы отличать их друг от друга. Это как если бы методы были бы файлами, а классы - папками, и мы бы раскладывали файлы по папкам.

Помимо просто организации методов, классы могут нести и информацию о данных, через переменные уровня класса - поля. Эти поля могут быть как примитивных типов (```int```, ```byte```, ```boolean``` и т. д.), так и ссылочных: стандартных и пользовательских (соответственно, ```String```, ```MyClass``` и другие).

Попробуем в нашей модели компьютера вынести данные о названии компонентов в поля и использовать в методах сообщений о включении/выключении имена из полей. 

> **N. B.** Интересный нюанс использования русскоязычных предложений в программе в том, что сейчас названия компонентов указываются в родительном падеже: "Включение _компьютера_", а выносить в переменную слово в не-именительном падеже как-то не комильфо: в переменной слово содержится в отрыве от контекста предложения и не очень-то понятно, чем обусловлен не-именительный падеж. А один из ключевых принципов написания программ заключается в том, что каждая отдельно взятая сущность программы должна быть сама по себе понятной и не вызывать вопросов. Можно, конечно, давать переменным сложные объясняющие названия, вроде ```componentNameInGenitive```, но в этом уже чувствуется какая-то избыточность. Можно хранить в переменных слова в именительном падеже, а в местах их использования трансформировать в нужный падеж, вроде такого: ```inGenitive(componentName)```. Но такая трансформация - сама по себе не тривиальная задача. Поэтому предлагаю упростить себе входные условия и переформулировать предложения так, чтобы там использовался именительный падеж, например: "Компьютер включается".

### Задача №4
- [x] Вынести названия компонентов компьютера в поля классов

Так же вернёмся к задаче №1, там нам требовалось написать такой код, чтобы строчка ```MySystem.myOut.myPrintln("Hello world");``` успешно компилировалась и выполнялась. Нам удалось её решить, заменив поле ```myOut``` на вложенный класс ```MyOut```. Теперь вернёмся к изначальной постановке условий и поле.

### Задача №5
- [x] Написать такой код, чтобы строчка ```MySystem.myOut.myPrintln("Hello world");``` успешно компилировалась и выполнялась

**Comment by Rideress** [comment]
Получается мне надо переписать код так чтобы у меня устройства были переменными, а не классами и был какой-то один общий метод который при помощи конкатенации выводил бы что данное устройство включено?

**Comment by acrm** [comment]
Пока классы сохраняются, только имена устройств выносятся в поля и выводятся в методах своих классов через конкатенацию.

**Comment by acrm** [comment]
:+1:
